site_name: 'Component documentation'

nav:
  - Home: index.md
  - API:
     Packages: packages.md
     Orders: orders.md
  - 'Integration with':
      Github: integration/github.md
      2: integration/github.md
  

plugins:
  - techdocs-core
  - search
